/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Connection;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;


/**
 *
 * @author ujjwal
 */
public class Admission extends javax.swing.JFrame {
    String Status;
    /**
     * Creates new form Admission
     */
    public Admission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicantid = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        applicantid2 = new javax.swing.JTextField();
        insertadmbtn = new javax.swing.JButton();
        accepted = new javax.swing.JRadioButton();
        rejected = new javax.swing.JRadioButton();
        admdashback = new javax.swing.JButton();
        deletevalue = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        applicantid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantidActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Applicant_Id");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Status");

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ADMISSION");
        jLabel1.setFocusable(false);

        applicantid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantid2ActionPerformed(evt);
            }
        });

        insertadmbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertadmbtn.setText("INSERT");
        insertadmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertadmbtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(accepted);
        accepted.setText("Accepted");

        buttonGroup1.add(rejected);
        rejected.setText("Rejected");

        admdashback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admdashback.setText("GO BACK");
        admdashback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admdashbackActionPerformed(evt);
            }
        });

        deletevalue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletevalue.setText("DELETE");
        deletevalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevalueActionPerformed(evt);
            }
        });

        jLabel3.setText("(Please enter applicant_id and click Delete) ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(applicantid2)))
                        .addGap(274, 274, 274))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertadmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(deletevalue, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(admdashback, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accepted)
                                        .addGap(50, 50, 50)
                                        .addComponent(rejected)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(applicantid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(accepted)
                    .addComponent(rejected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertadmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admdashback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletevalue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicantidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicantidActionPerformed

    private void applicantid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicantid2ActionPerformed

    private void insertadmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertadmbtnActionPerformed
       try {
             Class.forName("oracle.jdbc.driver.OracleDriver");																				
             String dbURL1 = "jdbc:oracle:thin:u2prajap/09101476@oracle.scs.ryerson.ca:1521:orcl";
	     Connection conn1 = DriverManager.getConnection(dbURL1);
             String query2 = "insert into admission(applicantid,status)values(?,?)";
             
              PreparedStatement pst = conn1.prepareStatement(query2);
              pst.setString(1,applicantid2.getText());
              if(accepted.isSelected()){
                 Status = "Accepted";
             }
              if(rejected.isSelected()){
                  Status = "Rejected";
              }
              pst.setString(2,Status);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(null, "Inserted Successfully!");
       }
                   catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    
             
    }//GEN-LAST:event_insertadmbtnActionPerformed

    private void admdashbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admdashbackActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_admdashbackActionPerformed

    private void deletevalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevalueActionPerformed
         try {
             Class.forName("oracle.jdbc.driver.OracleDriver");																				
             String dbURL1 = "jdbc:oracle:thin:u2prajap/09101476@oracle.scs.ryerson.ca:1521:orcl";
	     Connection conn2 = DriverManager.getConnection(dbURL1);
             String query = "delete from admission where applicantid = ?";
             PreparedStatement pst = conn2.prepareStatement(query);
             pst.setString(1,applicantid2.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Data Deleted Successfully");
    }//GEN-LAST:event_deletevalueActionPerformed
    catch (SQLException ex) {
            ex.printStackTrace();
        }
                  catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accepted;
    private javax.swing.JButton admdashback;
    private javax.swing.JTextField applicantid;
    private javax.swing.JTextField applicantid2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deletevalue;
    private javax.swing.JButton insertadmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rejected;
    // End of variables declaration//GEN-END:variables
}
